services:
  nginx:
    image: nginx:alpine
    container_name: visual_patrol_nginx
    ports:
      - "5000:5000"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src/frontend:/app/frontend:ro
    depends_on:
      - robot-a
    restart: unless-stopped

  robot-a:
    container_name: visual_patrol_robot_a
    build: .
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - DATA_DIR=/app/data
      - LOG_DIR=/app/logs
      - TZ=Asia/Taipei
      - ROBOT_ID=robot-a
      - ROBOT_NAME=Robot A
      - ROBOT_IP=192.168.50.133:26400
      - RELAY_SERVICE_URL=http://192.168.50.35:5020
    restart: unless-stopped

  # robot-b:
  #   container_name: visual_patrol_robot_b
  #   build: .
  #   volumes:
  #     - ./src:/app/src
  #     - ./data:/app/data
  #     - ./logs:/app/logs
  #   environment:
  #     - DATA_DIR=/app/data
  #     - LOG_DIR=/app/logs
  #     - TZ=Asia/Taipei
  #     - ROBOT_ID=robot-b
  #     - ROBOT_NAME=Robot B
  #     - ROBOT_IP=192.168.50.133:26400
  #   restart: unless-stopped

  # robot-c:
  #   container_name: visual_patrol_robot_c
  #   build: .
  #   volumes:
  #     - ./src:/app/src
  #     - ./data:/app/data
  #     - ./logs:/app/logs
  #   environment:
  #     - DATA_DIR=/app/data
  #     - LOG_DIR=/app/logs
  #     - TZ=Asia/Taipei
  #     - ROBOT_ID=robot-c
  #     - ROBOT_NAME=Robot C
  #     - ROBOT_IP=192.168.50.133:26400
  #   restart: unless-stopped
